programmer/olimexino-32u4 firmware: make it possible to use PlatformIO
This commit simplifies firmware build by using PlatformIO (https://platformio.org/).
PlatformIO makes it possible to build olimexino-32u4 firmware
using CLI interface without manual Arduino libraries setup.

SPIFlash library by Prajwal Bhattaram is outdated and is not available
via current 1.8.8 Arduino IDE. SPIFlash has been superseded by SPIMemory.

This commit imports SPIFlash 2.2.0 sources from SPIMemory github repo.

import howto:

  $ git clone -b v2.2.0 https://github.com/Marzogh/SPIMemory
  $ mkdir src
  $ cp SPIMemory/SPIFlash.cpp SPIMemory/SPIFlash.h src/

Necessary forward declaration are added to iceprog.ino to prevent
"was not declared in this scope" errors, e.g.

  src/iceprog.cpp:94:23: error: 'readSerialFrame' was not declared in this scope

Signed-off-by: Antony Pavlov <antonynpavlov@gmail.com>